#!/usr/bin/env bash
# setup-dev.sh — Bootstrap gmail-migrate development environment
#
# Detects whether running in Codespaces / Gitpod / local, then:
#   A) Prompts for tokens interactively (paste mode)
#   B) Fetches secrets from GitHub Secrets via GH_TOKEN
#
# Writes:  ui/.env.local
# Configs: ~/.kilo-code/config.json (KiloCode via OpenRouter)
#          ~/.claude/settings.json  (Claude Code OpenRouter entry, if key provided)
#
# Usage:
#   bash scripts/setup-dev.sh          # interactive mode
#   bash scripts/setup-dev.sh --gh     # fetch from GitHub Secrets
#   bash scripts/setup-dev.sh --check  # print readiness without writing anything

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/ui/.env.local"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

ok()   { echo -e "${GREEN}✅  $*${NC}"; }
warn() { echo -e "${YELLOW}⚠️   $*${NC}"; }
fail() { echo -e "${RED}❌  $*${NC}"; }

detect_env() {
  if [[ -n "${CODESPACE_NAME:-}" ]]; then echo "codespaces"
  elif [[ -n "${GITPOD_WORKSPACE_ID:-}" ]]; then echo "gitpod"
  else echo "local"
  fi
}

# ── Mode flags ────────────────────────────────────────────────────────────────
MODE="${1:-}"
ENV_TYPE="$(detect_env)"

echo ""
echo "═══════════════════════════════════════════"
echo "  gmail-migrate dev bootstrap"
echo "  Environment: $ENV_TYPE"
echo "═══════════════════════════════════════════"
echo ""

# ── check-only mode ───────────────────────────────────────────────────────────
if [[ "$MODE" == "--check" ]]; then
  echo "Checking required variables in $ENV_FILE ..."
  echo ""
  VARS=(WORKER_URL WORKER_AUTH_TOKEN GMAIL_SOURCE_USER GITHUB_TOKEN GITHUB_REPO)
  ALL_OK=true
  for var in "${VARS[@]}"; do
    val=$(grep -s "^${var}=" "$ENV_FILE" | cut -d= -f2-)
    if [[ -n "$val" ]]; then ok "$var"; else fail "$var (missing)"; ALL_OK=false; fi
  done
  echo ""
  if $ALL_OK; then ok "All required vars present"; else fail "Some vars missing — run setup-dev.sh"; fi
  exit 0
fi

# ── Skip if already configured ────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]] && grep -q "WORKER_URL=https" "$ENV_FILE" 2>/dev/null; then
  warn ".env.local already populated at $ENV_FILE"
  warn "Run with --check to verify, or delete the file to re-run setup."
  echo ""
  # Still proceed to configure tools
fi

# ── Fetch from GitHub Secrets (Mode B) ───────────────────────────────────────
if [[ "$MODE" == "--gh" ]]; then
  echo "Fetching secrets from GitHub Secrets (requires GH_TOKEN + gh CLI)..."
  if ! command -v gh &>/dev/null; then
    fail "gh CLI not installed. Install from https://cli.github.com/ then re-run."
    exit 1
  fi
  WORKER_URL=$(gh secret list -R "${GITHUB_REPO:-}" 2>/dev/null | grep WORKER_URL | head -1 || true)
  warn "GitHub Secrets API does not expose secret values — only names."
  warn "Use Mode A (paste) or configure Codespaces secrets at:"
  warn "  https://github.com/settings/codespaces"
  MODE=""
fi

# ── Interactive paste mode (Mode A) ──────────────────────────────────────────
read_secret() {
  local var="$1" prompt="$2" default="${3:-}"
  local existing
  existing=$(grep -s "^${var}=" "$ENV_FILE" | cut -d= -f2- || true)
  if [[ -n "$existing" ]]; then
    echo "  $var [already set, press Enter to keep]: "
    read -r val
    [[ -z "$val" ]] && echo "$val=$existing" && return
    echo "$val"
  else
    read -rp "  $prompt [$default]: " val
    val="${val:-$default}"
    echo "$val"
  fi
}

echo "Enter your secrets (paste values, or press Enter to skip optional ones):"
echo ""

WORKER_URL_VAL=$(read_secret WORKER_URL "CF Worker URL (e.g. https://your-worker.workers.dev)" "")
WORKER_AUTH_VAL=$(read_secret WORKER_AUTH_TOKEN "CF Worker auth token" "")
SOURCE_USER_VAL=$(read_secret GMAIL_SOURCE_USER "Source Gmail address (G1)" "")
GITHUB_TOKEN_VAL=$(read_secret GITHUB_TOKEN "GitHub personal access token" "")
GITHUB_REPO_VAL=$(read_secret GITHUB_REPO "GitHub repo (owner/name)" "aakifshamsi/gmail-migrate")
OPENROUTER_VAL=$(read_secret OPENROUTER_API_KEY "OpenRouter API key (optional — enables KiloCode)" "")

# ── Write .env.local ──────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup-dev.sh — DO NOT COMMIT
# Cloudflare Worker token vault
WORKER_URL=${WORKER_URL_VAL}
WORKER_AUTH_TOKEN=${WORKER_AUTH_VAL}

# Gmail source account
GMAIL_SOURCE_USER=${SOURCE_USER_VAL}

# GitHub Actions (for triggering migration workflows)
GITHUB_TOKEN=${GITHUB_TOKEN_VAL}
GITHUB_REPO=${GITHUB_REPO_VAL}

# Optional — enables token status checks in the UI
NEXT_PUBLIC_GITHUB_REPO=${GITHUB_REPO_VAL}
EOF

ok "Written $ENV_FILE"

# ── Configure KiloCode via OpenRouter ────────────────────────────────────────
if [[ -n "$OPENROUTER_VAL" ]]; then
  KILO_DIR="$HOME/.kilo-code"
  mkdir -p "$KILO_DIR"
  cat > "$KILO_DIR/config.json" <<EOF
{
  "provider": "openrouter",
  "openRouterApiKey": "${OPENROUTER_VAL}",
  "openRouterModelId": "anthropic/claude-sonnet-4-5",
  "maxTokens": 8192
}
EOF
  ok "KiloCode configured → OpenRouter (claude-sonnet-4-5)"

  # Also wire into Claude Code settings if present
  CLAUDE_SETTINGS="$HOME/.claude/settings.json"
  if [[ -f "$CLAUDE_SETTINGS" ]]; then
    warn "~/.claude/settings.json exists — add OPENROUTER_API_KEY manually or via /update-config"
  fi
else
  warn "OPENROUTER_API_KEY skipped — KiloCode will use default provider"
fi

# ── Readiness summary ─────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════"
echo "  Readiness summary"
echo "═══════════════════════════════════════════"
VARS=(WORKER_URL WORKER_AUTH_TOKEN GMAIL_SOURCE_USER GITHUB_TOKEN GITHUB_REPO)
ALL_OK=true
for var in "${VARS[@]}"; do
  val=$(grep -s "^${var}=" "$ENV_FILE" | cut -d= -f2-)
  if [[ -n "$val" ]]; then ok "$var"; else fail "$var (missing)"; ALL_OK=false; fi
done
echo ""
if $ALL_OK; then
  ok "Setup complete! Run: cd ui && npm run dev"
else
  warn "Some vars missing — re-run or edit $ENV_FILE manually"
fi
echo ""
